# Generated by Django 4.2.11 on 2024-04-21 15:52

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
