# Generated by Django 4.2.11 on 2024-05-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='course_images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(max_length=256),
        ),
    ]
