# Generated by Django 4.2.11 on 2024-05-14 15:17

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_hours_course_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
